apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpi-blinksticknano-tempgauge
  labels:
    app: rpi-blinksticknano-tempgauge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rpi-blinksticknano-tempgauge
  template:
    metadata:
      labels:
        app: rpi-blinksticknano-tempgauge
    spec:
      containers:
      - name: rpi-blinksticknano-tempgauge
        image: peterbb148/rpi-blinksticknano-tempgauge
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: MY_CPU_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: rpi-blinksticknano-tempgauge
                  resource: requests.cpu
            - name: MY_CPU_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: rpi-blinksticknano-tempgauge
                  resource: limits.cpu
            - name: MY_MEM_REQUEST
              valueFrom:
                resourceFieldRef:
                  containerName: rpi-blinksticknano-tempgauge
                  resource: requests.memory
            - name: MY_MEM_LIMIT
              valueFrom:
                resourceFieldRef:
                  containerName: rpi-blinksticknano-tempgauge
                  resource: limits.memory
---
apiVersion: v1
kind: Service
metadata:
  name: rpi-blinksticknano-tempgauge-service
spec:
  selector:
    app: rpi-blinksticknano-tempgauge
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rpi-blinksticknano-tempgauge-ingress
  annotations:
    kubernetes.io/ingress-class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: rpi-blinksticknano-tempgauge-service
          servicePort: 80